### PR TITLE
fix: remove focus-visible dependency

### LINKED ISSUE #11: auro-alerts: focus-visible is an unnecessary dependency
## Describe the bug
focus-visible is a peer dependency of this package, despite the fact that auro-alerts does not contain any focusable elements or focus-visible styles.

## To Reproduce
n/a

## Expected behavior
focus-visible is removed as a dependency and is not imported

## Screenshots
n/a

## Desktop (please complete the following information):
n/a

## Smartphone (please complete the following information):
n/a

## Additional context
Not sure if bug is the right classification for this, but it didn't feel like a feature request.

### PR DESCRIPTION
**Pull request by geoffrich**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #11 

## Summary:

Removes focus-visible as a dependency of auro-alerts.

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by geoffrich** [comment]
Tried to follow the PR/issue [labeling guidelines](https://auro.alaskaair.com/contributing/issues-prs-labels) on this one. Let me know if I should do anything differently next time.

**Comment by blackfalcon** [comment]
@geoffrich this looks good, but the `perf` prefix will not trigger a release. 

This is a bug and I am ok with treating it as so. Please update your commit from `perf` to `fix` and then we can release.

**Comment by geoffrich** [comment]
@blackfalcon commit has been updated

**Review by blackfalcon — APPROVED** [review]

**Pull request merged**
